export const HOME_MODULE = 'HOME_MODULE';

export const FETCH_HOME_DATA = 'FETCH_HOME_DATA';
export const SET_HOME_DATA = 'SET_HOME_DATA';

export const CATEGORY_MENU = 'CATEGORY_MENU';

export const LIST_SLIDERS = 'LIST_SLIDERS';

export const NEWS = 'NEWS';

export const TWO_BANNERS = 'TWO_BANNERS';
export const PROMOTION_BANNER = 'PROMOTION_BANNER';
export const LIST_SHOCKED_PRODUCTS = 'LIST_SHOCKED_PRODUCTS';
export const LIST_CATEGORIES = 'LIST_CATEGORIES';