export const HOME_MODULE = 'HOME_MODULE';

export const FETCH_HOME_DATA = 'FETCH_HOME_DATA';
export const SET_HOME_DATA = 'SET_HOME_DATA';

export const CATEGORY_MENU = 'CATEGORY_MENU';

export const LIST_SLIDERS = 'LIST_SLIDERS';

export const FETCH_LIST_HOME_BANNER_DESCRIPTIONS = 'FETCH_LIST_HOME_BANNER_DESCRIPTIONS';
export const SET_LIST_HOME_BANNER_DESCRIPTIONS = 'SET_LIST_HOME_BANNER_DESCRIPTIONS';
export const LIST_HOME_BANNER_DESCRIPTIONS = 'LIST_HOME_BANNER_DESCRIPTIONS';

export const FETCH_LIST_TECH_NEWS = 'FETCH_LIST_TECH_NEWS';
export const SET_LIST_TECH_NEWS = 'SET_LIST_TECH_NEWS';
export const LIST_TECH_NEWS = 'LIST_TECH_NEWS';

export const FETCH_TWO_BANNERS = 'FETCH_TWO_BANNERS';
export const SET_TWO_BANNERS = 'SET_TWO_BANNERS';
export const TWO_BANNERS = 'TWO_BANNERS';

export const FETCH_PROMOTION_BANNER = 'FETCH_PROMOTION_BANNER';
export const SET_PROMOTION_BANNER = 'SET_PROMOTION_BANNER';
export const PROMOTION_BANNER = 'PROMOTION_BANNER';

export const FETCH_LIST_SHOCKED_PRODUCTS = 'FETCH_LIST_SHOCKED_PRODUCTS';
export const SET_LIST_SHOCKED_PRODUCTS = 'SET_LIST_SHOCKED_PRODUCTS';
export const LIST_SHOCKED_PRODUCTS = 'LIST_SHOCKED_PRODUCTS';