export const HOME_MODULE = 'HOME_MODULE';
export const FETCH_LIST_CATEGORIES = 'FETCH_LIST_CATEGORIES';
export const SET_LIST_CATEGORIES = 'SET_LIST_CATEGORIES';
export const LIST_CATEGORIES = 'LIST_CATEGORIES';